// 
// Decompiled by Procyon v0.5.30
// 

package com.google.android.gms.internal;

import com.google.android.gms.common.api.v;
import com.google.android.gms.common.api.Status;
import com.google.android.gms.common.api.f;

public class bm extends f
{
    private final Status ul;
    
    public void gF(final v v) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
    
    Status yI() {
        return this.ul;
    }
}
